frontendBaseUrl: "https://rink-ui.vercel.app"
sheets:
  - name: instrument
    spreadsheetId: 1DMW9DfaLEMvNoL29Yvj7HR4e1SIGpn_QXvEhPdI4U8k
    tabs:
      - name: Main Data
        gid: 5695880
        excludeRowsWhere:
          - column: "id"
            equals: "id" 
      - name: Instituitiion list
        gid: 1583764603
