frontendBaseUrl: "https://rink-ui.vercel.app"
sheets:
  - name: instrument
    spreadsheetId: 1DMW9DfaLEMvNoL29Yvj7HR4e1SIGpn_QXvEhPdI4U8k
    tabs:
      - name: Main Data
        gid: 5695880
        excludeRowsWhere:
          - column: "id"
            equals: "id"
        splitColumns:
          - column: "tag"
            delimiter: ","
        imageColumns: "image_link"
      - name: Instituitiion list
        gid: 1583764603
    filterTaxonomy:
      standardized_district:
        "South Zone": ["Thiruvananthapuram", "Kollam", "Pathanamthitta"]
        "Central Zone": ["Ernakulam", "Thrissur", "Alappuzha", "Kottayam", "Idukki"]
        "North-Central Zone": ["Palakkad", "Malappuram"]
        "North Zone": ["Kozhikode", "Kannur", "Wayanad", "Kasaragod"]
      tag:
        "Life Sciences": ["genomics", "bioinformatics", "cell_culture", "microbiology"]
        "Material Sciences": ["metallurgy", "polymers", "nanotech", "surface_science"]
        "Electronics & Tech": ["semiconductors", "pcb_design", "rf_communications", "battery_tech"]
        "Environmental": ["environmental_science", "water_quality", "soil_analysis", "green_chem"]
        "Industrial / Commercial": ["food_safety", "textiles", "additive_mfg"]
