# IMPORTANT: If migrating to a custom domain (e.g. startupmission.in), you MUST update frontendBaseUrl
# otherwise AI search indexes will point to the wrong domain.
frontendBaseUrl: https://rink-ui.vercel.app
sheets:
  - name: instrument
    spreadsheetId: 1DMW9DfaLEMvNoL29Yvj7HR4e1SIGpn_QXvEhPdI4U8k
    tabs:
      - name: Main Data
        gid: 5695880
        excludeRowsWhere:
          - column: id
            equals: id
        splitColumns:
          - column: tag
            delimiter: ','
        imageColumns: image_link
      - name: Instituitiion list
        gid: 1583764603
        aiSearch:
          enabled: false
    filterTaxonomy:
      - id: standardized_district
        title: Districts
        gid: 5695880
        groups:
          South Zone:
            - Thiruvananthapuram
            - Kollam
            - Pathanamthitta
          Central Zone:
            - Ernakulam
            - Thrissur
            - Alappuzha
            - Kottayam
            - Idukki
          North-Central Zone:
            - Palakkad
            - Malappuram
          North Zone:
            - Kozhikode
            - Kannur
            - Wayanad
            - Kasaragod
      - id: correct_provider_key
        title: Institution Type
        gid: 5695880
        linkType: join
        joinSource:
          gid: 1583764603
          foreignKey: correct_provider_key
          groupByColumn: reason_classification
          displayColumn: institution_name
          groupByDelimiter: ','
          autoDiscover: true
        groups: {}
  - name: rink_tech
    spreadsheetId: 1HXlzT504-AhqzfU6Nm3bktAspIjaQm2l1z45qROZrFc
    tabs:
      - name: technologies
        gid: 0
        excludeRowsWhere:
          - column: technology_id
            equals: technology_id
        splitColumns:
          - column: keywords
            delimiter: ','
        imageColumns: image_url
      - name: institutions
        gid: 1979443544
        imageColumns: institution_logo_url
